### ISSUE TITLE
Test issues

### ISSUE THREAD

**Issue by xunil-cloud** [sonata-chen/test#1]
Testing messages.Another testing messages.

**Comment by sonata-chen** [comment]
@xunil-cload 



> Testing messages.Another testing messages.

感謝您提供的寶貴意見

**Comment by xunil-cloud** [comment]
Again, another test.

**Comment by xunil-cloud** [comment]
> test quote

**Comment by sonata-chen** [comment]
> good function

please try it.

**Comment by sonata-chen** [comment]
@xunil-cloud 
great

**Comment by sonata-chen** [comment]
###  **chek out our new wiki page!**

**Comment by xunil-cloud** [comment]
### header text
**bold text**
_italic text_
> insert a quote
[https://www.youtube.com](url)

- bulleted list1

**Comment by sonata-chen** [comment]
> > insert a quote
> > [https://www.youtube.com](url)

Your link is not working.

**Comment by xunil-cloud** [comment]
> > > insert a quote
> > > [https://www.youtube.com](url)
> 
> Your link is not working.

Why?

**Comment by sonata-chen** [comment]
`printf("hello world!");`
`int a = 0;`
[Mixing_Guide_2016.pdf](https://github.com/sonata-chen/test/files/3983210/Mixing_Guide_2016.pdf)
https://github.com/sonata-chen/test/blob/61c545997b056bb9fa618f8223142cc6e49425cc/LICENSE#L1-L6

https://github.com/sonata-chen/test/wiki
https://www.youtube.com/


This site was built using [GitHub Pages](https://pages.github.com/).
`This site was built using [GitHub Pages](https://pages.github.com/).`

**Comment by xunil-cloud** [comment]
[https://www.youtube.com/](url)

**Comment by xunil-cloud** [comment]
我打成`[https://www.youtube.com](url)`

**Comment by sonata-chen** [comment]
我一開始也是，明明就有寫(url)，還亂寫一通

**Comment by xunil-cloud** [comment]
I close this test issue.

**Comment by xunil-cloud** [comment]
I close this test issue.
